Implement dashboard
illfate2/dashboard pull request #1
Opened 2020-05-17 17:46 UTC by illfate2

2020-05-25 11:59 UTC, Paulbel requested changes

2020-05-25 11:59 UTC, Paulbel commented on src/sample/model/StudentInfo.java
> +    private SimpleIntegerProperty summary;
модель слишком привязана к библиотеке - это плохо, это скорее модель для Вашей таблицы, но не для всего приложения

2020-05-25 12:19 UTC, illfate2 commented on src/sample/model/StudentInfo.java
> +    private SimpleIntegerProperty summary;
@Paulbel, согласен, однако данные проперти инкапсулированы в класс и контракт взаимодействия более чем общий и даже при переезде на другую библиотеку не придется тут ничего менять, просто не увидел смысла плодить бессмысленные сущности

2020-06-03 10:36 UTC, Paulbel approved these changes
прислать демо

2020-06-03 11:25 UTC, merged